# Generated by Django 5.0.6 on 2024-05-28 09:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('image', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('rating_rate', models.FloatField()),
                ('rating_count', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
